### ISSUE TITLE
console commands

### ISSUE THREAD

**Issue by DemonRem** [AonaSuzutsuki/SavannahManager#4]
i mean all the tool are total grayed out i cant get character data , show commandlist , gray config is gray

**Comment by AonaSuzutsuki** [comment]
The "Command List" and "Config" are currently unsupported. They are available as reserved features, but due to my busy schedule, they have not been developed yet.
The problem of not being able to get the player list is due to a problem with the console logging method, so I'm working on a solution.

The greyed out functions in "Tools" can be used by enabling "Beta mode".
Please check "Enable Betamode" in "Tools" -> "Settings" -> "Others".

**Comment by DemonRem** [comment]
ok thanks .
